export const hrRoutes = {
  employees: "/employees",
  employeesCreate: "/employees/create",
  employeesEdit: "/employees/edit/:id",
  employeesShow: "/employees/show/:id",
  departments: "/departments",
  departmentsCreate: "/departments/create",
  departmentsEdit: "/departments/edit/:id",
  departmentsShow: "/departments/show/:id",
  leave: "/leave",
  leaveCreate: "/leave/create",
  leaveEdit: "/leave/edit/:id",
  leaveShow: "/leave/show/:id",
  orgChart: "/org-chart",
  leaveCalendar: "/leave-calendar",
} as const;
