// AUTO-GENERATED by the localization pipeline. Do not edit by hand.
import { starter as jaJP_starter } from "./ja-JP";
import { starter as koKR_starter } from "./ko-KR";
import { starter as zhTW_starter } from "./zh-TW";
import { starter as frFR_starter } from "./fr-FR";
import { starter as deDE_starter } from "./de-DE";
import { starter as esES_starter } from "./es-ES";
import { starter as ptBR_starter } from "./pt-BR";
import { starter as ruRU_starter } from "./ru-RU";
import { starter as itIT_starter } from "./it-IT";
import { starter as nlNL_starter } from "./nl-NL";
import { starter as trTR_starter } from "./tr-TR";
import { starter as plPL_starter } from "./pl-PL";
import { starter as viVN_starter } from "./vi-VN";
import { starter as thTH_starter } from "./th-TH";
import { starter as idID_starter } from "./id-ID";
import { starter as arEG_starter } from "./ar-EG";
import { starter as csCZ_starter } from "./cs-CZ";
import { starter as heIL_starter } from "./he-IL";
import { starter as hiIN_starter } from "./hi-IN";
import { starter as svSE_starter } from "./sv-SE";
import { starter as ukUA_starter } from "./uk-UA";
import { pagesLocale as jaJP_pagesLocale } from "./pages/ja-JP";
import { pagesLocale as koKR_pagesLocale } from "./pages/ko-KR";
import { pagesLocale as zhTW_pagesLocale } from "./pages/zh-TW";
import { pagesLocale as frFR_pagesLocale } from "./pages/fr-FR";
import { pagesLocale as deDE_pagesLocale } from "./pages/de-DE";
import { pagesLocale as esES_pagesLocale } from "./pages/es-ES";
import { pagesLocale as ptBR_pagesLocale } from "./pages/pt-BR";
import { pagesLocale as ruRU_pagesLocale } from "./pages/ru-RU";
import { pagesLocale as itIT_pagesLocale } from "./pages/it-IT";
import { pagesLocale as nlNL_pagesLocale } from "./pages/nl-NL";
import { pagesLocale as trTR_pagesLocale } from "./pages/tr-TR";
import { pagesLocale as plPL_pagesLocale } from "./pages/pl-PL";
import { pagesLocale as viVN_pagesLocale } from "./pages/vi-VN";
import { pagesLocale as thTH_pagesLocale } from "./pages/th-TH";
import { pagesLocale as idID_pagesLocale } from "./pages/id-ID";
import { pagesLocale as arEG_pagesLocale } from "./pages/ar-EG";
import { pagesLocale as csCZ_pagesLocale } from "./pages/cs-CZ";
import { pagesLocale as heIL_pagesLocale } from "./pages/he-IL";
import { pagesLocale as hiIN_pagesLocale } from "./pages/hi-IN";
import { pagesLocale as svSE_pagesLocale } from "./pages/sv-SE";
import { pagesLocale as ukUA_pagesLocale } from "./pages/uk-UA";

export const additionalTranslations: Record<string, Record<string, Record<string, string>>> = {
  "starter": {
    "ja-JP": { ...jaJP_starter, ...jaJP_pagesLocale },
    "ko-KR": { ...koKR_starter, ...koKR_pagesLocale },
    "zh-TW": { ...zhTW_starter, ...zhTW_pagesLocale },
    "fr-FR": { ...frFR_starter, ...frFR_pagesLocale },
    "de-DE": { ...deDE_starter, ...deDE_pagesLocale },
    "es-ES": { ...esES_starter, ...esES_pagesLocale },
    "pt-BR": { ...ptBR_starter, ...ptBR_pagesLocale },
    "ru-RU": { ...ruRU_starter, ...ruRU_pagesLocale },
    "it-IT": { ...itIT_starter, ...itIT_pagesLocale },
    "nl-NL": { ...nlNL_starter, ...nlNL_pagesLocale },
    "tr-TR": { ...trTR_starter, ...trTR_pagesLocale },
    "pl-PL": { ...plPL_starter, ...plPL_pagesLocale },
    "vi-VN": { ...viVN_starter, ...viVN_pagesLocale },
    "th-TH": { ...thTH_starter, ...thTH_pagesLocale },
    "id-ID": { ...idID_starter, ...idID_pagesLocale },
    "ar-EG": { ...arEG_starter, ...arEG_pagesLocale },
    "cs-CZ": { ...csCZ_starter, ...csCZ_pagesLocale },
    "he-IL": { ...heIL_starter, ...heIL_pagesLocale },
    "hi-IN": { ...hiIN_starter, ...hiIN_pagesLocale },
    "sv-SE": { ...svSE_starter, ...svSE_pagesLocale },
    "uk-UA": { ...ukUA_starter, ...ukUA_pagesLocale },
  },
};
